window.PRIMARY_ENGLISH_SCOPE = {
  1: {
    stage: 'Junior Primary · Foundations',
    level: 'P1',
    overview: 'Build confidence through sounds, familiar words and short everyday sentences.',
    vocabulary: ['greetings', 'family members', 'school and stationery', 'common animals', 'fruit and numbers', 'toys', 'colours', 'clothes'],
    wordBank: ['hello', 'goodbye', 'mother', 'father', 'pencil', 'book', 'cat', 'dog', 'apple', 'seven', 'ball', 'red', 'blue', 'shirt'],
    grammar: ['am / is / are', 'a / an / the', 'singular and plural nouns', 'personal pronouns', 'my / your / his / her', 'can / cannot', 'in / on / under / next to', 'What / Who / Where / How many'],
    reading: 'Read labels, picture books, rhymes and 50–80 word passages. Find familiar key words.',
    writing: 'Complete a sentence, describe a picture and write 1–3 linked sentences about familiar topics.',
    listening: 'Recognise letter sounds, follow simple classroom instructions and listen for names, colours and numbers.',
    speaking: 'Introduce yourself, answer simple questions and read a short dialogue aloud.',
    assessment: 'Use picture clues. Say the word softly, then find the matching letter pattern.'
  },
  2: {
    stage: 'Junior Primary · Everyday English',
    level: 'P2',
    overview: 'Use English for routines, needs and familiar places with growing sentence accuracy.',
    vocabulary: ['body parts', 'food and drinks', 'home rooms', 'public places', 'weather and seasons', 'daily routines'],
    wordBank: ['breakfast', 'water', 'kitchen', 'library', 'sunny', 'rainy', 'morning', 'evening', 'brush', 'walk', 'hungry', 'weekend', 'market', 'weather'],
    grammar: ['have / has', 'simple present tense', 'third-person -s', 'there is / there are', 'countable nouns', 'some / any', 'can / cannot', 'present continuous', 'days and time words'],
    reading: 'Read notices, timetables and 60–100 word descriptions. Match details to simple questions.',
    writing: 'Write 3–4 linked sentences about a daily routine, a favourite food or a familiar place.',
    listening: 'Listen for actions, times, food and weather details in short conversations.',
    speaking: 'Describe a picture using complete sentences and ask simple follow-up questions.',
    assessment: 'Look for the subject before choosing a verb. Check whether one person or many people are doing the action.'
  },
  3: {
    stage: 'Junior Primary · Connected Ideas',
    level: 'P3',
    overview: 'Connect simple ideas, describe experiences and begin to read short stories independently.',
    vocabulary: ['jobs', 'transport', 'hobbies and leisure', 'shapes and size', 'illness and feelings'],
    wordBank: ['doctor', 'driver', 'bus', 'train', 'museum', 'picnic', 'circle', 'heavy', 'headache', 'careful', 'excited', 'quiet', 'visit', 'together'],
    grammar: ['simple past tense', 'common irregular verbs', 'present continuous', 'comparatives', 'frequency adverbs', 'and / but / because', 'possessive nouns', 'movement prepositions', 'Why / How often'],
    reading: 'Read 80–120 word stories and short factual texts. Identify people, places, actions and sequence.',
    writing: 'Write a short diary entry or a 4-step picture story with a beginning, middle and ending.',
    listening: 'Listen to a short story and identify the setting, key actions and a character’s feeling.',
    speaking: 'Retell a familiar event in order using first, next and finally.',
    assessment: 'Circle time clues such as yesterday or last week. They often tell you which verb form to use.'
  },
  4: {
    stage: 'Upper Primary · Information and Organisation',
    level: 'P4',
    overview: 'Organise information clearly and use a broader range of tenses and language functions.',
    vocabulary: ['world festivals', 'cultures', 'health and habits', 'recycling and the environment', 'community facilities'],
    wordBank: ['festival', 'culture', 'healthy', 'exercise', 'recycle', 'energy', 'community', 'library', 'schedule', 'travel', 'uniform', 'useful', 'nature', 'pollution'],
    grammar: ['will / will not', 'be going to', 'present perfect introduction', 'should / must / must not', 'much / many / a few / a little', 'superlatives', 'adverbs of manner', 'if for everyday results', 'first / next / finally'],
    reading: 'Read emails, diaries, instructions and short information articles. Identify the purpose and organise details.',
    writing: 'Write structured paragraphs, practical messages and 60–90 word picture descriptions.',
    listening: 'Listen for the main idea and supporting details in a longer dialogue or a recorded story.',
    speaking: 'Give a prepared 1-minute talk about a familiar topic such as healthy habits or recycling.',
    assessment: 'Before listening, read the choices and predict the place, person or action you may hear.'
  },
  5: {
    stage: 'Upper Primary · Application and Inference',
    level: 'P5',
    overview: 'Compare tenses, infer meaning and write for different purposes with clear reasons.',
    vocabulary: ['world geography and travel', 'natural disasters', 'technology and future life', 'famous people and biographies'],
    wordBank: ['geography', 'journey', 'earthquake', 'flood', 'technology', 'digital', 'invent', 'future', 'biography', 'volunteer', 'environment', 'research', 'resource', 'responsible'],
    grammar: ['present perfect with already / yet / for / since', 'present, past and future contrast', 'passive voice introduction', 'first conditional', 'relative clauses', 'indirect questions', 'comparatives and superlatives', 'because / so / although', 'to-infinitive'],
    reading: 'Read reports, posters, charts, news-style texts and multiple paragraphs. Make simple inferences from context.',
    writing: 'Write 80–120 word emails, narratives, reports and suggestions with paragraphs and connectives.',
    listening: 'Take simple notes from longer dialogues, broadcasts or stories and notice a speaker’s purpose.',
    speaking: 'Give an opinion in a group discussion and support it with one or two clear reasons.',
    assessment: 'For tense questions, find time words first: yesterday signals past; since and for often signal present perfect.'
  },
  6: {
    stage: 'Upper Primary · Secondary School Readiness',
    level: 'P6',
    overview: 'Integrate language knowledge, inference and independent expression in preparation for secondary school.',
    vocabulary: ['secondary-school life', 'dreams and careers', 'teenage challenges', 'volunteer service', 'social topics'],
    wordBank: ['aspiration', 'career', 'challenge', 'decision', 'benefit', 'effective', 'opinion', 'perspective', 'recommend', 'solution', 'sustainable', 'participate', 'consequence', 'variety'],
    grammar: ['past continuous with simple past', 'present perfect versus simple past', 'passive voice', 'second conditional', 'gerunds and infinitives', 'reported speech introduction', 'reflexive and possessive pronouns', 'although / however / therefore', 'compound and complex sentences'],
    reading: 'Read multi-format texts, viewpoints and longer passages. Infer attitude, pronoun reference and the writer’s main message.',
    writing: 'Write 100–150 word emails, narratives, articles and proposals with an engaging opening and organised paragraphs.',
    listening: 'Identify the main message, detailed information and speaker attitude in broadcasts or recorded discussions.',
    speaking: 'Deliver a structured 1–2 minute presentation and respond thoughtfully in a group discussion.',
    assessment: 'Keep the tense consistent in a story. Use linking words to show sequence, contrast and cause.'
  }
};
